#if 0
//
// FX Version: fx_4_0
// Child effect (requires effect pool): false
//
// 1 local buffer(s)
//
cbuffer paramsOnlyOnce
{
    float4  bloomGatherSamples[2];      // Offset:    0, size:   32
    float4  bloomBlurSamples[15];       // Offset:   32, size:  240
    float   bloomBlurWeights[15];       // Offset:  272, size:  228
    float2  bloomBlurPixelDir;          // Offset:  500, size:    8
    float4  screenSizeInv;              // Offset:  512, size:   16
    float2  filterSizeInv;              // Offset:  528, size:    8
    float   motionBlurFrameWeight;      // Offset:  536, size:    4
    float   loadProgress = 0;           // Offset:  540, size:    4
}

//
// 4 local object(s)
//
Texture2D bufferSceneColor;
Texture2D bufferFilter;
SamplerState samplerSceneColor
{
    AddressU = uint(CLAMP /* 3 */);
    AddressV = uint(CLAMP /* 3 */);
    Filter   = uint(MIN_MAG_MIP_LINEAR /* 21 */);
};
SamplerState samplerFilter
{
    AddressU = uint(CLAMP /* 3 */);
    AddressV = uint(CLAMP /* 3 */);
    Filter   = uint(MIN_MAG_MIP_LINEAR /* 21 */);
};

//
// 1 technique(s)
//
technique10 PostFX
{
    pass Gather
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyz         0     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xy          1     NONE   float   xy  
            //
            vs_4_0
            dcl_input v0.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xy
            mov o0.xy, v0.xyxx
            mov o0.zw, l(0,0,0,1.000000)
            mad o1.xy, v0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
            ret 
            // Approximately 4 instruction slots used
                    
        };
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer paramsOnlyOnce
            // {
            //
            //   float4 bloomGatherSamples[2];      // Offset:    0 Size:    32
            //   float4 bloomBlurSamples[15];       // Offset:   32 Size:   240 [unused]
            //   float bloomBlurWeights[15];        // Offset:  272 Size:   228 [unused]
            //   float2 bloomBlurPixelDir;          // Offset:  500 Size:     8 [unused]
            //   float4 screenSizeInv;              // Offset:  512 Size:    16 [unused]
            //   float2 filterSizeInv;              // Offset:  528 Size:     8
            //   float motionBlurFrameWeight;       // Offset:  536 Size:     4 [unused]
            //   float loadProgress;                // Offset:  540 Size:     4 [unused]
            //      = 0x00000000 
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim Slot Elements
            // ------------------------------ ---------- ------- ----------- ---- --------
            // samplerSceneColor                 sampler      NA          NA    0        1
            // bufferSceneColor                  texture  float4          2d    0        1
            // paramsOnlyOnce                    cbuffer      NA          NA    0        1
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xy  
            // TEXCOORD                 0   xy          1     NONE   float       
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer cb0[34], dynamicIndexed
            dcl_sampler s0, mode_default
            dcl_resource_texture2d (float,float,float,float) t0
            dcl_input_ps_siv linear noperspective v0.xy, position
            dcl_output o0.xyzw
            dcl_temps 4
            mov r0.xyzw, l(0,0,0,0)
            loop 
              ige r1.x, r0.w, l(2)
              breakc_nz r1.x
              mad r1.xyzw, v0.xyxy, cb0[33].xyxy, cb0[r0.w + 0].xywz
              sample r2.xyzw, r1.xyxx, t0.xyzw, s0
              lt r3.xyz, l(1.000000, 1.000000, 1.000000, 0.000000), r2.xyzx
              or r1.x, r3.y, r3.x
              or r1.x, r3.z, r1.x
              and r2.xyz, r2.xyzx, r1.xxxx
              add r2.xyz, r0.xyzx, r2.xyzx
              sample r1.xyzw, r1.zwzz, t0.xyzw, s0
              lt r3.xyz, l(1.000000, 1.000000, 1.000000, 0.000000), r1.xyzx
              or r1.w, r3.y, r3.x
              or r1.w, r3.z, r1.w
              and r1.xyz, r1.xyzx, r1.wwww
              add r0.xyz, r1.xyzx, r2.xyzx
              iadd r0.w, r0.w, l(1)
            endloop 
            mul r0.xyz, r0.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000)
            mul o0.xyz, r0.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000)
            mov o0.w, l(0)
            ret 
            // Approximately 23 instruction slots used
                    
        };
    }

    pass Blur
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyz         0     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xy          1     NONE   float   xy  
            //
            vs_4_0
            dcl_input v0.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xy
            mov o0.xy, v0.xyxx
            mov o0.zw, l(0,0,0,1.000000)
            mad o1.xy, v0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
            ret 
            // Approximately 4 instruction slots used
                    
        };
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer paramsOnlyOnce
            // {
            //
            //   float4 bloomGatherSamples[2];      // Offset:    0 Size:    32 [unused]
            //   float4 bloomBlurSamples[15];       // Offset:   32 Size:   240
            //   float bloomBlurWeights[15];        // Offset:  272 Size:   228
            //   float2 bloomBlurPixelDir;          // Offset:  500 Size:     8
            //   float4 screenSizeInv;              // Offset:  512 Size:    16 [unused]
            //   float2 filterSizeInv;              // Offset:  528 Size:     8
            //   float motionBlurFrameWeight;       // Offset:  536 Size:     4 [unused]
            //   float loadProgress;                // Offset:  540 Size:     4 [unused]
            //      = 0x00000000 
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim Slot Elements
            // ------------------------------ ---------- ------- ----------- ---- --------
            // samplerFilter                     sampler      NA          NA    0        1
            // bufferFilter                      texture  float4          2d    0        1
            // paramsOnlyOnce                    cbuffer      NA          NA    0        1
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xy  
            // TEXCOORD                 0   xy          1     NONE   float       
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer cb0[34], dynamicIndexed
            dcl_sampler s0, mode_default
            dcl_resource_texture2d (float,float,float,float) t0
            dcl_input_ps_siv linear noperspective v0.xy, position
            dcl_output o0.xyzw
            dcl_temps 3
            mov r0.xyzw, l(0,0,0,0)
            mov r1.x, l(0)
            loop 
              ige r1.y, r1.x, l(15)
              breakc_nz r1.y
              mul r1.yz, cb0[31].yyzy, cb0[r1.x + 2].xxyx
              mad r1.yz, v0.xxyx, cb0[33].xxyx, r1.yyzy
              sample r2.xyzw, r1.yzyy, t0.xyzw, s0
              mad r0.xyzw, r2.xyzw, cb0[r1.x + 17].xxxx, r0.xyzw
              iadd r1.x, r1.x, l(1)
            endloop 
            mov o0.xyzw, r0.xyzw
            ret 
            // Approximately 13 instruction slots used
                    
        };
    }

    pass Combine
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyz         0     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xy          1     NONE   float   xy  
            //
            vs_4_0
            dcl_input v0.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xy
            mov o0.xy, v0.xyxx
            mov o0.zw, l(0,0,0,1.000000)
            mad o1.xy, v0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
            ret 
            // Approximately 4 instruction slots used
                    
        };
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer paramsOnlyOnce
            // {
            //
            //   float4 bloomGatherSamples[2];      // Offset:    0 Size:    32 [unused]
            //   float4 bloomBlurSamples[15];       // Offset:   32 Size:   240 [unused]
            //   float bloomBlurWeights[15];        // Offset:  272 Size:   228 [unused]
            //   float2 bloomBlurPixelDir;          // Offset:  500 Size:     8 [unused]
            //   float4 screenSizeInv;              // Offset:  512 Size:    16 [unused]
            //   float2 filterSizeInv;              // Offset:  528 Size:     8 [unused]
            //   float motionBlurFrameWeight;       // Offset:  536 Size:     4 [unused]
            //   float loadProgress;                // Offset:  540 Size:     4
            //      = 0x00000000 
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim Slot Elements
            // ------------------------------ ---------- ------- ----------- ---- --------
            // samplerSceneColor                 sampler      NA          NA    0        1
            // samplerFilter                     sampler      NA          NA    1        1
            // bufferSceneColor                  texture  float4          2d    0        1
            // bufferFilter                      texture  float4          2d    1        1
            // paramsOnlyOnce                    cbuffer      NA          NA    0        1
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float       
            // TEXCOORD                 0   xy          1     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer cb0[34], immediateIndexed
            dcl_sampler s0, mode_default
            dcl_sampler s1, mode_default
            dcl_resource_texture2d (float,float,float,float) t0
            dcl_resource_texture2d (float,float,float,float) t1
            dcl_input_ps linear v1.xy
            dcl_output o0.xyzw
            dcl_temps 5
            ge r0.x, l(0.564000), v1.y
            ge r0.yz, v1.yyxy, l(0.000000, 0.436000, 0.100000, 0.000000)
            and r0.x, r0.x, r0.y
            and r0.x, r0.z, r0.x
            mad r0.y, cb0[33].w, l(0.800000), l(0.100000)
            lt r0.y, v1.x, r0.y
            and r0.x, r0.y, r0.x
            add r0.y, -v1.x, l(1.000000)
            mul r0.y, r0.y, l(120.000000)
            sincos r0.y, null, r0.y
            add r0.z, -cb0[33].w, l(0.800000)
            lt r0.y, r0.z, r0.y
            and r0.x, r0.x, r0.y
            ge r1.xyzw, v1.yxxy, l(0.400000, 0.080000, 0.910000, 0.582000)
            ge r2.xyzw, l(0.600000, 0.920000, 0.090000, 0.418000), v1.yxxy
            or r0.y, r1.z, r2.z
            or r0.y, r2.w, r0.y
            or r0.y, r1.w, r0.y
            or r0.x, r0.x, r0.y
            and r0.xyz, r0.xxxx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
            mov r0.w, l(1.000000)
            sample r3.xyzw, v1.xyxx, t0.xyzw, s0
            sample r4.xyzw, v1.xyxx, t1.xyzw, s1
            mad r3.xyzw, r4.xyzw, l(4.000000, 4.000000, 4.000000, 4.000000), r3.xyzw
            add r0.xyzw, r0.xyzw, r3.xyzw
            and r1.x, r1.x, r2.x
            and r1.x, r1.y, r1.x
            and r1.x, r2.y, r1.x
            movc r0.xyzw, r1.xxxx, r0.xyzw, r3.xyzw
            lt r1.x, l(0.000000), cb0[33].w
            movc o0.xyzw, r1.xxxx, r0.xyzw, r3.xyzw
            ret 
            // Approximately 32 instruction slots used
                    
        };
    }

    pass MotionBlur
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyz         0     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xy          1     NONE   float   xy  
            //
            vs_4_0
            dcl_input v0.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xy
            mov o0.xy, v0.xyxx
            mov o0.zw, l(0,0,0,1.000000)
            mad o1.xy, v0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
            ret 
            // Approximately 4 instruction slots used
                    
        };
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer paramsOnlyOnce
            // {
            //
            //   float4 bloomGatherSamples[2];      // Offset:    0 Size:    32 [unused]
            //   float4 bloomBlurSamples[15];       // Offset:   32 Size:   240 [unused]
            //   float bloomBlurWeights[15];        // Offset:  272 Size:   228 [unused]
            //   float2 bloomBlurPixelDir;          // Offset:  500 Size:     8 [unused]
            //   float4 screenSizeInv;              // Offset:  512 Size:    16 [unused]
            //   float2 filterSizeInv;              // Offset:  528 Size:     8 [unused]
            //   float motionBlurFrameWeight;       // Offset:  536 Size:     4
            //   float loadProgress;                // Offset:  540 Size:     4 [unused]
            //      = 0x00000000 
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim Slot Elements
            // ------------------------------ ---------- ------- ----------- ---- --------
            // samplerSceneColor                 sampler      NA          NA    0        1
            // bufferSceneColor                  texture  float4          2d    0        1
            // paramsOnlyOnce                    cbuffer      NA          NA    0        1
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float       
            // TEXCOORD                 0   xy          1     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer cb0[34], immediateIndexed
            dcl_sampler s0, mode_default
            dcl_resource_texture2d (float,float,float,float) t0
            dcl_input_ps linear v1.xy
            dcl_output o0.xyzw
            dcl_temps 1
            sample r0.xyzw, v1.xyxx, t0.xyzw, s0
            mov o0.xyz, r0.xyzx
            mov o0.w, cb0[33].z
            ret 
            // Approximately 4 instruction slots used
                    
        };
    }

}

#endif

const BYTE gCompiledShader_PostProcess[] =
{
     68,  88,  66,  67,  34,  45, 
     72, 159,   9, 131,  91,  18, 
    182,  96, 110, 214, 186,  75, 
    223, 212,   1,   0,   0,   0, 
     76,  40,   0,   0,   1,   0, 
      0,   0,  36,   0,   0,   0, 
     70,  88,  49,  48,  32,  40, 
      0,   0,   1,  16, 255, 254, 
      1,   0,   0,   0,   8,   0, 
      0,   0,   4,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0, 104,  37, 
      0,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   8,   0, 
      0,   0,   8,   0,   0,   0, 
      0,   0,   0,   0, 112,  97, 
    114,  97, 109, 115,  79, 110, 
    108, 121,  79, 110,  99, 101, 
      0, 102, 108, 111,  97, 116, 
     52,   0,  19,   0,   0,   0, 
      1,   0,   0,   0,   2,   0, 
      0,   0,  32,   0,   0,   0, 
     16,   0,   0,   0,  32,   0, 
      0,   0,  10,  33,   0,   0, 
     98, 108, 111, 111, 109,  71, 
     97, 116, 104, 101, 114,  83, 
     97, 109, 112, 108, 101, 115, 
      0,  19,   0,   0,   0,   1, 
      0,   0,   0,  15,   0,   0, 
      0, 240,   0,   0,   0,  16, 
      0,   0,   0, 240,   0,   0, 
      0,  10,  33,   0,   0,  98, 
    108, 111, 111, 109,  66, 108, 
    117, 114,  83,  97, 109, 112, 
    108, 101, 115,   0, 102, 108, 
    111,  97, 116,   0, 118,   0, 
      0,   0,   1,   0,   0,   0, 
     15,   0,   0,   0, 228,   0, 
      0,   0,  16,   0,   0,   0, 
     60,   0,   0,   0,   9,   9, 
      0,   0,  98, 108, 111, 111, 
    109,  66, 108, 117, 114,  87, 
    101, 105, 103, 104, 116, 115, 
      0, 102, 108, 111,  97, 116, 
     50,   0, 169,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   8,   0,   0,   0, 
     16,   0,   0,   0,   8,   0, 
      0,   0,  10,  17,   0,   0, 
     98, 108, 111, 111, 109,  66, 
    108, 117, 114,  80, 105, 120, 
    101, 108,  68, 105, 114,   0, 
     19,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
     16,   0,   0,   0,  16,   0, 
      0,   0,  16,   0,   0,   0, 
     10,  33,   0,   0, 115,  99, 
    114, 101, 101, 110,  83, 105, 
    122, 101,  73, 110, 118,   0, 
    102, 105, 108, 116, 101, 114, 
     83, 105, 122, 101,  73, 110, 
    118,   0, 118,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   4,   0,   0,   0, 
     16,   0,   0,   0,   4,   0, 
      0,   0,   9,   9,   0,   0, 
    109, 111, 116, 105, 111, 110, 
     66, 108, 117, 114,  70, 114, 
     97, 109, 101,  87, 101, 105, 
    103, 104, 116,   0, 108, 111, 
     97, 100,  80, 114, 111, 103, 
    114, 101, 115, 115,   0,   0, 
      0,   0,   0,  84, 101, 120, 
    116, 117, 114, 101,  50,  68, 
      0,  89,   1,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  12,   0,   0,   0,  98, 
    117, 102, 102, 101, 114,  83, 
     99, 101, 110, 101,  67, 111, 
    108, 111, 114,   0,  98, 117, 
    102, 102, 101, 114,  70, 105, 
    108, 116, 101, 114,   0,  83, 
     97, 109, 112, 108, 101, 114, 
     83, 116,  97, 116, 101,   0, 
    157,   1,   0,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     21,   0,   0,   0, 115,  97, 
    109, 112, 108, 101, 114,  83, 
     99, 101, 110, 101,  67, 111, 
    108, 111, 114,   0,   1,   0, 
      0,   0,   2,   0,   0,   0, 
      3,   0,   0,   0,   1,   0, 
      0,   0,   2,   0,   0,   0, 
      3,   0,   0,   0,   1,   0, 
      0,   0,   2,   0,   0,   0, 
     21,   0,   0,   0, 115,  97, 
    109, 112, 108, 101, 114,  70, 
    105, 108, 116, 101, 114,   0, 
      1,   0,   0,   0,   2,   0, 
      0,   0,   3,   0,   0,   0, 
      1,   0,   0,   0,   2,   0, 
      0,   0,   3,   0,   0,   0, 
      1,   0,   0,   0,   2,   0, 
      0,   0,  21,   0,   0,   0, 
     80, 111, 115, 116,  70,  88, 
      0,  71,  97, 116, 104, 101, 
    114,   0,  64,   2,   0,   0, 
     68,  88,  66,  67, 228,  77, 
     10,   2, 174,  22,  22, 158, 
    217, 105, 111, 180,  28, 223, 
     97, 175,   1,   0,   0,   0, 
     64,   2,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    140,   0,   0,   0, 192,   0, 
      0,   0,  24,   1,   0,   0, 
    196,   1,   0,   0,  82,  68, 
     69,  70,  80,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     28,   0,   0,   0,   0,   4, 
    254, 255,   0,   1,   0,   0, 
     28,   0,   0,   0,  77, 105, 
     99, 114, 111, 115, 111, 102, 
    116,  32,  40,  82,  41,  32, 
     72,  76,  83,  76,  32,  83, 
    104,  97, 100, 101, 114,  32, 
     67, 111, 109, 112, 105, 108, 
    101, 114,  32,  57,  46,  51, 
     48,  46,  57,  54,  48,  46, 
     56,  50,  50,  57,   0, 171, 
    171, 171,  73,  83,  71,  78, 
     44,   0,   0,   0,   1,   0, 
      0,   0,   8,   0,   0,   0, 
     32,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,   7,   3,   0,   0, 
     80,  79,  83,  73,  84,  73, 
     79,  78,   0, 171, 171, 171, 
     79,  83,  71,  78,  80,   0, 
      0,   0,   2,   0,   0,   0, 
      8,   0,   0,   0,  56,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
     15,   0,   0,   0,  68,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   1,   0,   0,   0, 
      3,  12,   0,   0,  83,  86, 
     95,  80, 111, 115, 105, 116, 
    105, 111, 110,   0,  84,  69, 
     88,  67,  79,  79,  82,  68, 
      0, 171, 171, 171,  83,  72, 
     68,  82, 164,   0,   0,   0, 
     64,   0,   1,   0,  41,   0, 
      0,   0,  95,   0,   0,   3, 
     50,  16,  16,   0,   0,   0, 
      0,   0, 103,   0,   0,   4, 
    242,  32,  16,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
    101,   0,   0,   3,  50,  32, 
     16,   0,   1,   0,   0,   0, 
     54,   0,   0,   5,  50,  32, 
     16,   0,   0,   0,   0,   0, 
     70,  16,  16,   0,   0,   0, 
      0,   0,  54,   0,   0,   8, 
    194,  32,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 128,  63,  50,   0, 
      0,  15,  50,  32,  16,   0, 
      1,   0,   0,   0,  70,  16, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,  63,   0,   0,   0, 191, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,  63,   0,   0, 
      0,  63,   0,   0,   0,   0, 
      0,   0,   0,   0,  62,   0, 
      0,   1,  83,  84,  65,  84, 
    116,   0,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     60,   2,   0,   0,   0,   0, 
      0,   0, 212,   6,   0,   0, 
     68,  88,  66,  67,  15, 228, 
      1,  44,  48,   2, 178, 230, 
    169, 130, 225,  80, 159,  34, 
     25,  69,   1,   0,   0,   0, 
    212,   6,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    240,   2,   0,   0,  72,   3, 
      0,   0, 124,   3,   0,   0, 
     88,   6,   0,   0,  82,  68, 
     69,  70, 180,   2,   0,   0, 
      1,   0,   0,   0, 176,   0, 
      0,   0,   3,   0,   0,   0, 
     28,   0,   0,   0,   0,   4, 
    255, 255,   0,   1,   0,   0, 
    128,   2,   0,   0, 124,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
    142,   0,   0,   0,   2,   0, 
      0,   0,   5,   0,   0,   0, 
      4,   0,   0,   0, 255, 255, 
    255, 255,   0,   0,   0,   0, 
      1,   0,   0,   0,  12,   0, 
      0,   0, 159,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0, 115,  97, 
    109, 112, 108, 101, 114,  83, 
     99, 101, 110, 101,  67, 111, 
    108, 111, 114,   0,  98, 117, 
    102, 102, 101, 114,  83,  99, 
    101, 110, 101,  67, 111, 108, 
    111, 114,   0, 112,  97, 114, 
     97, 109, 115,  79, 110, 108, 
    121,  79, 110,  99, 101,   0, 
    171, 171, 159,   0,   0,   0, 
      8,   0,   0,   0, 200,   0, 
      0,   0,  32,   2,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 136,   1,   0,   0, 
      0,   0,   0,   0,  32,   0, 
      0,   0,   2,   0,   0,   0, 
    156,   1,   0,   0,   0,   0, 
      0,   0, 172,   1,   0,   0, 
     32,   0,   0,   0, 240,   0, 
      0,   0,   0,   0,   0,   0, 
    192,   1,   0,   0,   0,   0, 
      0,   0, 208,   1,   0,   0, 
     16,   1,   0,   0, 228,   0, 
      0,   0,   0,   0,   0,   0, 
    228,   1,   0,   0,   0,   0, 
      0,   0, 244,   1,   0,   0, 
    244,   1,   0,   0,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   2,   0,   0,   0,   0, 
      0,   0,  24,   2,   0,   0, 
      0,   2,   0,   0,  16,   0, 
      0,   0,   0,   0,   0,   0, 
     40,   2,   0,   0,   0,   0, 
      0,   0,  56,   2,   0,   0, 
     16,   2,   0,   0,   8,   0, 
      0,   0,   2,   0,   0,   0, 
      8,   2,   0,   0,   0,   0, 
      0,   0,  70,   2,   0,   0, 
     24,   2,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
     92,   2,   0,   0,   0,   0, 
      0,   0, 108,   2,   0,   0, 
     28,   2,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
     92,   2,   0,   0, 124,   2, 
      0,   0,  98, 108, 111, 111, 
    109,  71,  97, 116, 104, 101, 
    114,  83,  97, 109, 112, 108, 
    101, 115,   0, 171,   1,   0, 
      3,   0,   1,   0,   4,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   0,  98, 108, 111, 111, 
    109,  66, 108, 117, 114,  83, 
     97, 109, 112, 108, 101, 115, 
      0, 171, 171, 171,   1,   0, 
      3,   0,   1,   0,   4,   0, 
     15,   0,   0,   0,   0,   0, 
      0,   0,  98, 108, 111, 111, 
    109,  66, 108, 117, 114,  87, 
    101, 105, 103, 104, 116, 115, 
      0, 171, 171, 171,   0,   0, 
      3,   0,   1,   0,   1,   0, 
     15,   0,   0,   0,   0,   0, 
      0,   0,  98, 108, 111, 111, 
    109,  66, 108, 117, 114,  80, 
    105, 120, 101, 108,  68, 105, 
    114,   0, 171, 171,   1,   0, 
      3,   0,   1,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 115,  99, 114, 101, 
    101, 110,  83, 105, 122, 101, 
     73, 110, 118,   0, 171, 171, 
      1,   0,   3,   0,   1,   0, 
      4,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 102, 105, 
    108, 116, 101, 114,  83, 105, 
    122, 101,  73, 110, 118,   0, 
    109, 111, 116, 105, 111, 110, 
     66, 108, 117, 114,  70, 114, 
     97, 109, 101,  87, 101, 105, 
    103, 104, 116,   0,   0,   0, 
      3,   0,   1,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 108, 111,  97, 100, 
     80, 114, 111, 103, 114, 101, 
    115, 115,   0, 171, 171, 171, 
      0,   0,   0,   0,  77, 105, 
     99, 114, 111, 115, 111, 102, 
    116,  32,  40,  82,  41,  32, 
     72,  76,  83,  76,  32,  83, 
    104,  97, 100, 101, 114,  32, 
     67, 111, 109, 112, 105, 108, 
    101, 114,  32,  57,  46,  51, 
     48,  46,  57,  54,  48,  46, 
     56,  50,  50,  57,   0, 171, 
    171, 171,  73,  83,  71,  78, 
     80,   0,   0,   0,   2,   0, 
      0,   0,   8,   0,   0,   0, 
     56,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,  15,   3,   0,   0, 
     68,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   1,   0, 
      0,   0,   3,   0,   0,   0, 
     83,  86,  95,  80, 111, 115, 
    105, 116, 105, 111, 110,   0, 
     84,  69,  88,  67,  79,  79, 
     82,  68,   0, 171, 171, 171, 
     79,  83,  71,  78,  44,   0, 
      0,   0,   1,   0,   0,   0, 
      8,   0,   0,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
     15,   0,   0,   0,  83,  86, 
     95,  84,  97, 114, 103, 101, 
    116,   0, 171, 171,  83,  72, 
     68,  82, 212,   2,   0,   0, 
     64,   0,   0,   0, 181,   0, 
      0,   0,  89,   8,   0,   4, 
     70, 142,  32,   0,   0,   0, 
      0,   0,  34,   0,   0,   0, 
     90,   0,   0,   3,   0,  96, 
     16,   0,   0,   0,   0,   0, 
     88,  24,   0,   4,   0, 112, 
     16,   0,   0,   0,   0,   0, 
     85,  85,   0,   0, 100,  32, 
      0,   4,  50,  16,  16,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0, 101,   0,   0,   3, 
    242,  32,  16,   0,   0,   0, 
      0,   0, 104,   0,   0,   2, 
      4,   0,   0,   0,  54,   0, 
      0,   8, 242,   0,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     48,   0,   0,   1,  33,   0, 
      0,   7,  18,   0,  16,   0, 
      1,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   2,   0, 
      0,   0,   3,   0,   4,   3, 
     10,   0,  16,   0,   1,   0, 
      0,   0,  50,   0,   0,  12, 
    242,   0,  16,   0,   1,   0, 
      0,   0,  70,  20,  16,   0, 
      0,   0,   0,   0,  70, 132, 
     32,   0,   0,   0,   0,   0, 
     33,   0,   0,   0,  70, 139, 
     32,   4,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,  69,   0,   0,   9, 
    242,   0,  16,   0,   2,   0, 
      0,   0,  70,   0,  16,   0, 
      1,   0,   0,   0,  70, 126, 
     16,   0,   0,   0,   0,   0, 
      0,  96,  16,   0,   0,   0, 
      0,   0,  49,   0,   0,  10, 
    114,   0,  16,   0,   3,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0, 128,  63, 
      0,   0,   0,   0,  70,   2, 
     16,   0,   2,   0,   0,   0, 
     60,   0,   0,   7,  18,   0, 
     16,   0,   1,   0,   0,   0, 
     26,   0,  16,   0,   3,   0, 
      0,   0,  10,   0,  16,   0, 
      3,   0,   0,   0,  60,   0, 
      0,   7,  18,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16,   0,   1,   0, 
      0,   0,   1,   0,   0,   7, 
    114,   0,  16,   0,   2,   0, 
      0,   0,  70,   2,  16,   0, 
      2,   0,   0,   0,   6,   0, 
     16,   0,   1,   0,   0,   0, 
      0,   0,   0,   7, 114,   0, 
     16,   0,   2,   0,   0,   0, 
     70,   2,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      2,   0,   0,   0,  69,   0, 
      0,   9, 242,   0,  16,   0, 
      1,   0,   0,   0, 230,  10, 
     16,   0,   1,   0,   0,   0, 
     70, 126,  16,   0,   0,   0, 
      0,   0,   0,  96,  16,   0, 
      0,   0,   0,   0,  49,   0, 
      0,  10, 114,   0,  16,   0, 
      3,   0,   0,   0,   2,  64, 
      0,   0,   0,   0, 128,  63, 
      0,   0, 128,  63,   0,   0, 
    128,  63,   0,   0,   0,   0, 
     70,   2,  16,   0,   1,   0, 
      0,   0,  60,   0,   0,   7, 
    130,   0,  16,   0,   1,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  10,   0, 
     16,   0,   3,   0,   0,   0, 
     60,   0,   0,   7, 130,   0, 
     16,   0,   1,   0,   0,   0, 
     42,   0,  16,   0,   3,   0, 
      0,   0,  58,   0,  16,   0, 
      1,   0,   0,   0,   1,   0, 
      0,   7, 114,   0,  16,   0, 
      1,   0,   0,   0,  70,   2, 
     16,   0,   1,   0,   0,   0, 
    246,  15,  16,   0,   1,   0, 
      0,   0,   0,   0,   0,   7, 
    114,   0,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      1,   0,   0,   0,  70,   2, 
     16,   0,   2,   0,   0,   0, 
     30,   0,   0,   7, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      1,   0,   0,   0,  22,   0, 
      0,   1,  56,   0,   0,  10, 
    114,   0,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   0,   0, 128,  62, 
      0,   0, 128,  62,   0,   0, 
    128,  62,   0,   0,   0,   0, 
     56,   0,   0,  10, 114,  32, 
     16,   0,   0,   0,   0,   0, 
     70,   2,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128,  62,   0,   0, 
    128,  62,   0,   0, 128,  62, 
      0,   0,   0,   0,  54,   0, 
      0,   5, 130,  32,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     62,   0,   0,   1,  83,  84, 
     65,  84, 116,   0,   0,   0, 
     23,   0,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   6,   0, 
      0,   0,   2,   0,   0,   0, 
      6,   0,   0,   0,   1,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   2,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   9,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 136,   4,   0,   0, 
      0,   0,   0,   0,  66, 108, 
    117, 114,   0,  64,   2,   0, 
      0,  68,  88,  66,  67, 228, 
     77,  10,   2, 174,  22,  22, 
    158, 217, 105, 111, 180,  28, 
    223,  97, 175,   1,   0,   0, 
      0,  64,   2,   0,   0,   5, 
      0,   0,   0,  52,   0,   0, 
      0, 140,   0,   0,   0, 192, 
      0,   0,   0,  24,   1,   0, 
      0, 196,   1,   0,   0,  82, 
     68,  69,  70,  80,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,  28,   0,   0,   0,   0, 
      4, 254, 255,   0,   1,   0, 
      0,  28,   0,   0,   0,  77, 
    105,  99, 114, 111, 115, 111, 
    102, 116,  32,  40,  82,  41, 
     32,  72,  76,  83,  76,  32, 
     83, 104,  97, 100, 101, 114, 
     32,  67, 111, 109, 112, 105, 
    108, 101, 114,  32,  57,  46, 
     51,  48,  46,  57,  54,  48, 
     46,  56,  50,  50,  57,   0, 
    171, 171, 171,  73,  83,  71, 
     78,  44,   0,   0,   0,   1, 
      0,   0,   0,   8,   0,   0, 
      0,  32,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,   7,   3,   0, 
      0,  80,  79,  83,  73,  84, 
     73,  79,  78,   0, 171, 171, 
    171,  79,  83,  71,  78,  80, 
      0,   0,   0,   2,   0,   0, 
      0,   8,   0,   0,   0,  56, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,  15,   0,   0,   0,  68, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   1,   0,   0, 
      0,   3,  12,   0,   0,  83, 
     86,  95,  80, 111, 115, 105, 
    116, 105, 111, 110,   0,  84, 
     69,  88,  67,  79,  79,  82, 
     68,   0, 171, 171, 171,  83, 
     72,  68,  82, 164,   0,   0, 
      0,  64,   0,   1,   0,  41, 
      0,   0,   0,  95,   0,   0, 
      3,  50,  16,  16,   0,   0, 
      0,   0,   0, 103,   0,   0, 
      4, 242,  32,  16,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0, 101,   0,   0,   3,  50, 
     32,  16,   0,   1,   0,   0, 
      0,  54,   0,   0,   5,  50, 
     32,  16,   0,   0,   0,   0, 
      0,  70,  16,  16,   0,   0, 
      0,   0,   0,  54,   0,   0, 
      8, 194,  32,  16,   0,   0, 
      0,   0,   0,   2,  64,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 128,  63,  50, 
      0,   0,  15,  50,  32,  16, 
      0,   1,   0,   0,   0,  70, 
     16,  16,   0,   0,   0,   0, 
      0,   2,  64,   0,   0,   0, 
      0,   0,  63,   0,   0,   0, 
    191,   0,   0,   0,   0,   0, 
      0,   0,   0,   2,  64,   0, 
      0,   0,   0,   0,  63,   0, 
      0,   0,  63,   0,   0,   0, 
      0,   0,   0,   0,   0,  62, 
      0,   0,   1,  83,  84,  65, 
     84, 116,   0,   0,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 109,  11,   0,   0,   0, 
      0,   0,   0, 144,   5,   0, 
      0,  68,  88,  66,  67, 158, 
    117,  41, 135,  57,  10, 228, 
    212, 246,  40, 142, 217, 188, 
    186, 164, 240,   1,   0,   0, 
      0, 144,   5,   0,   0,   5, 
      0,   0,   0,  52,   0,   0, 
      0, 232,   2,   0,   0,  64, 
      3,   0,   0, 116,   3,   0, 
      0,  20,   5,   0,   0,  82, 
     68,  69,  70, 172,   2,   0, 
      0,   1,   0,   0,   0, 168, 
      0,   0,   0,   3,   0,   0, 
      0,  28,   0,   0,   0,   0, 
      4, 255, 255,   0,   1,   0, 
      0, 120,   2,   0,   0, 124, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0, 138,   0,   0,   0,   2, 
      0,   0,   0,   5,   0,   0, 
      0,   4,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0,   1,   0,   0,   0,  12, 
      0,   0,   0, 151,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0, 115, 
     97, 109, 112, 108, 101, 114, 
     70, 105, 108, 116, 101, 114, 
      0,  98, 117, 102, 102, 101, 
    114,  70, 105, 108, 116, 101, 
    114,   0, 112,  97, 114,  97, 
    109, 115,  79, 110, 108, 121, 
     79, 110,  99, 101,   0, 171, 
    171, 151,   0,   0,   0,   8, 
      0,   0,   0, 192,   0,   0, 
      0,  32,   2,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 128,   1,   0,   0,   0, 
      0,   0,   0,  32,   0,   0, 
      0,   0,   0,   0,   0, 148, 
      1,   0,   0,   0,   0,   0, 
      0, 164,   1,   0,   0,  32, 
      0,   0,   0, 240,   0,   0, 
      0,   2,   0,   0,   0, 184, 
      1,   0,   0,   0,   0,   0, 
      0, 200,   1,   0,   0,  16, 
      1,   0,   0, 228,   0,   0, 
      0,   2,   0,   0,   0, 220, 
      1,   0,   0,   0,   0,   0, 
      0, 236,   1,   0,   0, 244, 
      1,   0,   0,   8,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      2,   0,   0,   0,   0,   0, 
      0,  16,   2,   0,   0,   0, 
      2,   0,   0,  16,   0,   0, 
      0,   0,   0,   0,   0,  32, 
      2,   0,   0,   0,   0,   0, 
      0,  48,   2,   0,   0,  16, 
      2,   0,   0,   8,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      2,   0,   0,   0,   0,   0, 
      0,  62,   2,   0,   0,  24, 
      2,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0,  84, 
      2,   0,   0,   0,   0,   0, 
      0, 100,   2,   0,   0,  28, 
      2,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0,  84, 
      2,   0,   0, 116,   2,   0, 
      0,  98, 108, 111, 111, 109, 
     71,  97, 116, 104, 101, 114, 
     83,  97, 109, 112, 108, 101, 
    115,   0, 171,   1,   0,   3, 
      0,   1,   0,   4,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,  98, 108, 111, 111, 109, 
     66, 108, 117, 114,  83,  97, 
    109, 112, 108, 101, 115,   0, 
    171, 171, 171,   1,   0,   3, 
      0,   1,   0,   4,   0,  15, 
      0,   0,   0,   0,   0,   0, 
      0,  98, 108, 111, 111, 109, 
     66, 108, 117, 114,  87, 101, 
    105, 103, 104, 116, 115,   0, 
    171, 171, 171,   0,   0,   3, 
      0,   1,   0,   1,   0,  15, 
      0,   0,   0,   0,   0,   0, 
      0,  98, 108, 111, 111, 109, 
     66, 108, 117, 114,  80, 105, 
    120, 101, 108,  68, 105, 114, 
      0, 171, 171,   1,   0,   3, 
      0,   1,   0,   2,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 115,  99, 114, 101, 101, 
    110,  83, 105, 122, 101,  73, 
    110, 118,   0, 171, 171,   1, 
      0,   3,   0,   1,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 102, 105, 108, 
    116, 101, 114,  83, 105, 122, 
    101,  73, 110, 118,   0, 109, 
    111, 116, 105, 111, 110,  66, 
    108, 117, 114,  70, 114,  97, 
    109, 101,  87, 101, 105, 103, 
    104, 116,   0,   0,   0,   3, 
      0,   1,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 108, 111,  97, 100,  80, 
    114, 111, 103, 114, 101, 115, 
    115,   0, 171, 171, 171,   0, 
      0,   0,   0,  77, 105,  99, 
    114, 111, 115, 111, 102, 116, 
     32,  40,  82,  41,  32,  72, 
     76,  83,  76,  32,  83, 104, 
     97, 100, 101, 114,  32,  67, 
    111, 109, 112, 105, 108, 101, 
    114,  32,  57,  46,  51,  48, 
     46,  57,  54,  48,  46,  56, 
     50,  50,  57,   0, 171, 171, 
    171,  73,  83,  71,  78,  80, 
      0,   0,   0,   2,   0,   0, 
      0,   8,   0,   0,   0,  56, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,  15,   3,   0,   0,  68, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   1,   0,   0, 
      0,   3,   0,   0,   0,  83, 
     86,  95,  80, 111, 115, 105, 
    116, 105, 111, 110,   0,  84, 
     69,  88,  67,  79,  79,  82, 
     68,   0, 171, 171, 171,  79, 
     83,  71,  78,  44,   0,   0, 
      0,   1,   0,   0,   0,   8, 
      0,   0,   0,  32,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,  15, 
      0,   0,   0,  83,  86,  95, 
     84,  97, 114, 103, 101, 116, 
      0, 171, 171,  83,  72,  68, 
     82, 152,   1,   0,   0,  64, 
      0,   0,   0, 102,   0,   0, 
      0,  89,   8,   0,   4,  70, 
    142,  32,   0,   0,   0,   0, 
      0,  34,   0,   0,   0,  90, 
      0,   0,   3,   0,  96,  16, 
      0,   0,   0,   0,   0,  88, 
     24,   0,   4,   0, 112,  16, 
      0,   0,   0,   0,   0,  85, 
     85,   0,   0, 100,  32,   0, 
      4,  50,  16,  16,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0, 101,   0,   0,   3, 242, 
     32,  16,   0,   0,   0,   0, 
      0, 104,   0,   0,   2,   3, 
      0,   0,   0,  54,   0,   0, 
      8, 242,   0,  16,   0,   0, 
      0,   0,   0,   2,  64,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,  54, 
      0,   0,   5,  18,   0,  16, 
      0,   1,   0,   0,   0,   1, 
     64,   0,   0,   0,   0,   0, 
      0,  48,   0,   0,   1,  33, 
      0,   0,   7,  34,   0,  16, 
      0,   1,   0,   0,   0,  10, 
      0,  16,   0,   1,   0,   0, 
      0,   1,  64,   0,   0,  15, 
      0,   0,   0,   3,   0,   4, 
      3,  26,   0,  16,   0,   1, 
      0,   0,   0,  56,   0,   0, 
     11,  98,   0,  16,   0,   1, 
      0,   0,   0,  86, 134,  32, 
      0,   0,   0,   0,   0,  31, 
      0,   0,   0,   6, 129,  32, 
      6,   0,   0,   0,   0,   2, 
      0,   0,   0,  10,   0,  16, 
      0,   1,   0,   0,   0,  50, 
      0,   0,  10,  98,   0,  16, 
      0,   1,   0,   0,   0,   6, 
     17,  16,   0,   0,   0,   0, 
      0,   6, 129,  32,   0,   0, 
      0,   0,   0,  33,   0,   0, 
      0,  86,   6,  16,   0,   1, 
      0,   0,   0,  69,   0,   0, 
      9, 242,   0,  16,   0,   2, 
      0,   0,   0, 150,   5,  16, 
      0,   1,   0,   0,   0,  70, 
    126,  16,   0,   0,   0,   0, 
      0,   0,  96,  16,   0,   0, 
      0,   0,   0,  50,   0,   0, 
     12, 242,   0,  16,   0,   0, 
      0,   0,   0,  70,  14,  16, 
      0,   2,   0,   0,   0,   6, 
    128,  32,   6,   0,   0,   0, 
      0,  17,   0,   0,   0,  10, 
      0,  16,   0,   1,   0,   0, 
      0,  70,  14,  16,   0,   0, 
      0,   0,   0,  30,   0,   0, 
      7,  18,   0,  16,   0,   1, 
      0,   0,   0,  10,   0,  16, 
      0,   1,   0,   0,   0,   1, 
     64,   0,   0,   1,   0,   0, 
      0,  22,   0,   0,   1,  54, 
      0,   0,   5, 242,  32,  16, 
      0,   0,   0,   0,   0,  70, 
     14,  16,   0,   0,   0,   0, 
      0,  62,   0,   0,   1,  83, 
     84,  65,  84, 116,   0,   0, 
      0,  13,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,   2,   0,   0,   0,   1, 
      0,   0,   0,   2,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,  12, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 185,  13,   0, 
      0,   0,   0,   0,   0,  67, 
    111, 109,  98, 105, 110, 101, 
      0,  64,   2,   0,   0,  68, 
     88,  66,  67, 228,  77,  10, 
      2, 174,  22,  22, 158, 217, 
    105, 111, 180,  28, 223,  97, 
    175,   1,   0,   0,   0,  64, 
      2,   0,   0,   5,   0,   0, 
      0,  52,   0,   0,   0, 140, 
      0,   0,   0, 192,   0,   0, 
      0,  24,   1,   0,   0, 196, 
      1,   0,   0,  82,  68,  69, 
     70,  80,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,  28, 
      0,   0,   0,   0,   4, 254, 
    255,   0,   1,   0,   0,  28, 
      0,   0,   0,  77, 105,  99, 
    114, 111, 115, 111, 102, 116, 
     32,  40,  82,  41,  32,  72, 
     76,  83,  76,  32,  83, 104, 
     97, 100, 101, 114,  32,  67, 
    111, 109, 112, 105, 108, 101, 
    114,  32,  57,  46,  51,  48, 
     46,  57,  54,  48,  46,  56, 
     50,  50,  57,   0, 171, 171, 
    171,  73,  83,  71,  78,  44, 
      0,   0,   0,   1,   0,   0, 
      0,   8,   0,   0,   0,  32, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,   7,   3,   0,   0,  80, 
     79,  83,  73,  84,  73,  79, 
     78,   0, 171, 171, 171,  79, 
     83,  71,  78,  80,   0,   0, 
      0,   2,   0,   0,   0,   8, 
      0,   0,   0,  56,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,  15, 
      0,   0,   0,  68,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   1,   0,   0,   0,   3, 
     12,   0,   0,  83,  86,  95, 
     80, 111, 115, 105, 116, 105, 
    111, 110,   0,  84,  69,  88, 
     67,  79,  79,  82,  68,   0, 
    171, 171, 171,  83,  72,  68, 
     82, 164,   0,   0,   0,  64, 
      0,   1,   0,  41,   0,   0, 
      0,  95,   0,   0,   3,  50, 
     16,  16,   0,   0,   0,   0, 
      0, 103,   0,   0,   4, 242, 
     32,  16,   0,   0,   0,   0, 
      0,   1,   0,   0,   0, 101, 
      0,   0,   3,  50,  32,  16, 
      0,   1,   0,   0,   0,  54, 
      0,   0,   5,  50,  32,  16, 
      0,   0,   0,   0,   0,  70, 
     16,  16,   0,   0,   0,   0, 
      0,  54,   0,   0,   8, 194, 
     32,  16,   0,   0,   0,   0, 
      0,   2,  64,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 128,  63,  50,   0,   0, 
     15,  50,  32,  16,   0,   1, 
      0,   0,   0,  70,  16,  16, 
      0,   0,   0,   0,   0,   2, 
     64,   0,   0,   0,   0,   0, 
     63,   0,   0,   0, 191,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   2,  64,   0,   0,   0, 
      0,   0,  63,   0,   0,   0, 
     63,   0,   0,   0,   0,   0, 
      0,   0,   0,  62,   0,   0, 
      1,  83,  84,  65,  84, 116, 
      0,   0,   0,   4,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,  93, 
     19,   0,   0,   0,   0,   0, 
      0, 168,   8,   0,   0,  68, 
     88,  66,  67,  77,  67,  35, 
     50,  93, 249, 236,  50, 174, 
     29,  47,  50,  79,  49, 105, 
     14,   1,   0,   0,   0, 168, 
      8,   0,   0,   5,   0,   0, 
      0,  52,   0,   0,   0,  76, 
      3,   0,   0, 164,   3,   0, 
      0, 216,   3,   0,   0,  44, 
      8,   0,   0,  82,  68,  69, 
     70,  16,   3,   0,   0,   1, 
      0,   0,   0,  12,   1,   0, 
      0,   5,   0,   0,   0,  28, 
      0,   0,   0,   0,   4, 255, 
    255,   0,   1,   0,   0, 220, 
      2,   0,   0, 188,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0, 206, 
      0,   0,   0,   3,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   1,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0, 220,   0,   0,   0,   2, 
      0,   0,   0,   5,   0,   0, 
      0,   4,   0,   0,   0, 255, 
    255, 255, 255,   0,   0,   0, 
      0,   1,   0,   0,   0,  12, 
      0,   0,   0, 237,   0,   0, 
      0,   2,   0,   0,   0,   5, 
      0,   0,   0,   4,   0,   0, 
      0, 255, 255, 255, 255,   1, 
      0,   0,   0,   1,   0,   0, 
      0,  12,   0,   0,   0, 250, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0, 115,  97, 109, 112, 108, 
    101, 114,  83,  99, 101, 110, 
    101,  67, 111, 108, 111, 114, 
      0, 115,  97, 109, 112, 108, 
    101, 114,  70, 105, 108, 116, 
    101, 114,   0,  98, 117, 102, 
    102, 101, 114,  83,  99, 101, 
    110, 101,  67, 111, 108, 111, 
    114,   0,  98, 117, 102, 102, 
    101, 114,  70, 105, 108, 116, 
    101, 114,   0, 112,  97, 114, 
     97, 109, 115,  79, 110, 108, 
    121,  79, 110,  99, 101,   0, 
    171, 171, 171, 250,   0,   0, 
      0,   8,   0,   0,   0,  36, 
      1,   0,   0,  32,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 228,   1,   0, 
      0,   0,   0,   0,   0,  32, 
      0,   0,   0,   0,   0,   0, 
      0, 248,   1,   0,   0,   0, 
      0,   0,   0,   8,   2,   0, 
      0,  32,   0,   0,   0, 240, 
      0,   0,   0,   0,   0,   0, 
      0,  28,   2,   0,   0,   0, 
      0,   0,   0,  44,   2,   0, 
      0,  16,   1,   0,   0, 228, 
      0,   0,   0,   0,   0,   0, 
      0,  64,   2,   0,   0,   0, 
      0,   0,   0,  80,   2,   0, 
      0, 244,   1,   0,   0,   8, 
      0,   0,   0,   0,   0,   0, 
      0, 100,   2,   0,   0,   0, 
      0,   0,   0, 116,   2,   0, 
      0,   0,   2,   0,   0,  16, 
      0,   0,   0,   0,   0,   0, 
      0, 132,   2,   0,   0,   0, 
      0,   0,   0, 148,   2,   0, 
      0,  16,   2,   0,   0,   8, 
      0,   0,   0,   0,   0,   0, 
      0, 100,   2,   0,   0,   0, 
      0,   0,   0, 162,   2,   0, 
      0,  24,   2,   0,   0,   4, 
      0,   0,   0,   0,   0,   0, 
      0, 184,   2,   0,   0,   0, 
      0,   0,   0, 200,   2,   0, 
      0,  28,   2,   0,   0,   4, 
      0,   0,   0,   2,   0,   0, 
      0, 184,   2,   0,   0, 216, 
      2,   0,   0,  98, 108, 111, 
    111, 109,  71,  97, 116, 104, 
    101, 114,  83,  97, 109, 112, 
    108, 101, 115,   0, 171,   1, 
      0,   3,   0,   1,   0,   4, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,  98, 108, 111, 
    111, 109,  66, 108, 117, 114, 
     83,  97, 109, 112, 108, 101, 
    115,   0, 171, 171, 171,   1, 
      0,   3,   0,   1,   0,   4, 
      0,  15,   0,   0,   0,   0, 
      0,   0,   0,  98, 108, 111, 
    111, 109,  66, 108, 117, 114, 
     87, 101, 105, 103, 104, 116, 
    115,   0, 171, 171, 171,   0, 
      0,   3,   0,   1,   0,   1, 
      0,  15,   0,   0,   0,   0, 
      0,   0,   0,  98, 108, 111, 
    111, 109,  66, 108, 117, 114, 
     80, 105, 120, 101, 108,  68, 
    105, 114,   0, 171, 171,   1, 
      0,   3,   0,   1,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 115,  99, 114, 
    101, 101, 110,  83, 105, 122, 
    101,  73, 110, 118,   0, 171, 
    171,   1,   0,   3,   0,   1, 
      0,   4,   0,   0,   0,   0, 
      0,   0,   0,   0,   0, 102, 
    105, 108, 116, 101, 114,  83, 
    105, 122, 101,  73, 110, 118, 
      0, 109, 111, 116, 105, 111, 
    110,  66, 108, 117, 114,  70, 
    114,  97, 109, 101,  87, 101, 
    105, 103, 104, 116,   0,   0, 
      0,   3,   0,   1,   0,   1, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0, 108, 111,  97, 
    100,  80, 114, 111, 103, 114, 
    101, 115, 115,   0, 171, 171, 
    171,   0,   0,   0,   0,  77, 
    105,  99, 114, 111, 115, 111, 
    102, 116,  32,  40,  82,  41, 
     32,  72,  76,  83,  76,  32, 
     83, 104,  97, 100, 101, 114, 
     32,  67, 111, 109, 112, 105, 
    108, 101, 114,  32,  57,  46, 
     51,  48,  46,  57,  54,  48, 
     46,  56,  50,  50,  57,   0, 
    171, 171, 171,  73,  83,  71, 
     78,  80,   0,   0,   0,   2, 
      0,   0,   0,   8,   0,   0, 
      0,  56,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   0,  15,   0,   0, 
      0,  68,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   3,   0,   0,   0,   1, 
      0,   0,   0,   3,   3,   0, 
      0,  83,  86,  95,  80, 111, 
    115, 105, 116, 105, 111, 110, 
      0,  84,  69,  88,  67,  79, 
     79,  82,  68,   0, 171, 171, 
    171,  79,  83,  71,  78,  44, 
      0,   0,   0,   1,   0,   0, 
      0,   8,   0,   0,   0,  32, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   3, 
      0,   0,   0,   0,   0,   0, 
      0,  15,   0,   0,   0,  83, 
     86,  95,  84,  97, 114, 103, 
    101, 116,   0, 171, 171,  83, 
     72,  68,  82,  76,   4,   0, 
      0,  64,   0,   0,   0,  19, 
      1,   0,   0,  89,   0,   0, 
      4,  70, 142,  32,   0,   0, 
      0,   0,   0,  34,   0,   0, 
      0,  90,   0,   0,   3,   0, 
     96,  16,   0,   0,   0,   0, 
      0,  90,   0,   0,   3,   0, 
     96,  16,   0,   1,   0,   0, 
      0,  88,  24,   0,   4,   0, 
    112,  16,   0,   0,   0,   0, 
      0,  85,  85,   0,   0,  88, 
     24,   0,   4,   0, 112,  16, 
      0,   1,   0,   0,   0,  85, 
     85,   0,   0,  98,  16,   0, 
      3,  50,  16,  16,   0,   1, 
      0,   0,   0, 101,   0,   0, 
      3, 242,  32,  16,   0,   0, 
      0,   0,   0, 104,   0,   0, 
      2,   5,   0,   0,   0,  29, 
      0,   0,   7,  18,   0,  16, 
      0,   0,   0,   0,   0,   1, 
     64,   0,   0,  78,  98,  16, 
     63,  26,  16,  16,   0,   1, 
      0,   0,   0,  29,   0,   0, 
     10,  98,   0,  16,   0,   0, 
      0,   0,   0,  86,  20,  16, 
      0,   1,   0,   0,   0,   2, 
     64,   0,   0,   0,   0,   0, 
      0, 100,  59, 223,  62, 205, 
    204, 204,  61,   0,   0,   0, 
      0,   1,   0,   0,   7,  18, 
      0,  16,   0,   0,   0,   0, 
      0,  10,   0,  16,   0,   0, 
      0,   0,   0,  26,   0,  16, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   7,  18,   0,  16, 
      0,   0,   0,   0,   0,  42, 
      0,  16,   0,   0,   0,   0, 
      0,  10,   0,  16,   0,   0, 
      0,   0,   0,  50,   0,   0, 
     10,  34,   0,  16,   0,   0, 
      0,   0,   0,  58, 128,  32, 
      0,   0,   0,   0,   0,  33, 
      0,   0,   0,   1,  64,   0, 
      0, 205, 204,  76,  63,   1, 
     64,   0,   0, 205, 204, 204, 
     61,  49,   0,   0,   7,  34, 
      0,  16,   0,   0,   0,   0, 
      0,  10,  16,  16,   0,   1, 
      0,   0,   0,  26,   0,  16, 
      0,   0,   0,   0,   0,   1, 
      0,   0,   7,  18,   0,  16, 
      0,   0,   0,   0,   0,  26, 
      0,  16,   0,   0,   0,   0, 
      0,  10,   0,  16,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      8,  34,   0,  16,   0,   0, 
      0,   0,   0,  10,  16,  16, 
    128,  65,   0,   0,   0,   1, 
      0,   0,   0,   1,  64,   0, 
      0,   0,   0, 128,  63,  56, 
      0,   0,   7,  34,   0,  16, 
      0,   0,   0,   0,   0,  26, 
      0,  16,   0,   0,   0,   0, 
      0,   1,  64,   0,   0,   0, 
      0, 240,  66,  77,   0,   0, 
      6,  34,   0,  16,   0,   0, 
      0,   0,   0,   0, 208,   0, 
      0,  26,   0,  16,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      9,  66,   0,  16,   0,   0, 
      0,   0,   0,  58, 128,  32, 
    128,  65,   0,   0,   0,   0, 
      0,   0,   0,  33,   0,   0, 
      0,   1,  64,   0,   0, 205, 
    204,  76,  63,  49,   0,   0, 
      7,  34,   0,  16,   0,   0, 
      0,   0,   0,  42,   0,  16, 
      0,   0,   0,   0,   0,  26, 
      0,  16,   0,   0,   0,   0, 
      0,   1,   0,   0,   7,  18, 
      0,  16,   0,   0,   0,   0, 
      0,  10,   0,  16,   0,   0, 
      0,   0,   0,  26,   0,  16, 
      0,   0,   0,   0,   0,  29, 
      0,   0,  10, 242,   0,  16, 
      0,   1,   0,   0,   0,  22, 
     20,  16,   0,   1,   0,   0, 
      0,   2,  64,   0,   0, 205, 
    204, 204,  62,  10, 215, 163, 
     61, 195, 245, 104,  63, 244, 
    253,  20,  63,  29,   0,   0, 
     10, 242,   0,  16,   0,   2, 
      0,   0,   0,   2,  64,   0, 
      0, 154, 153,  25,  63,  31, 
    133, 107,  63, 236,  81, 184, 
     61,  25,   4, 214,  62,  22, 
     20,  16,   0,   1,   0,   0, 
      0,  60,   0,   0,   7,  34, 
      0,  16,   0,   0,   0,   0, 
      0,  42,   0,  16,   0,   1, 
      0,   0,   0,  42,   0,  16, 
      0,   2,   0,   0,   0,  60, 
      0,   0,   7,  34,   0,  16, 
      0,   0,   0,   0,   0,  58, 
      0,  16,   0,   2,   0,   0, 
      0,  26,   0,  16,   0,   0, 
      0,   0,   0,  60,   0,   0, 
      7,  34,   0,  16,   0,   0, 
      0,   0,   0,  58,   0,  16, 
      0,   1,   0,   0,   0,  26, 
      0,  16,   0,   0,   0,   0, 
      0,  60,   0,   0,   7,  18, 
      0,  16,   0,   0,   0,   0, 
      0,  10,   0,  16,   0,   0, 
      0,   0,   0,  26,   0,  16, 
      0,   0,   0,   0,   0,   1, 
      0,   0,  10, 114,   0,  16, 
      0,   0,   0,   0,   0,   6, 
      0,  16,   0,   0,   0,   0, 
      0,   2,  64,   0,   0,   0, 
      0, 128,  63,   0,   0, 128, 
     63,   0,   0, 128,  63,   0, 
      0,   0,   0,  54,   0,   0, 
      5, 130,   0,  16,   0,   0, 
      0,   0,   0,   1,  64,   0, 
      0,   0,   0, 128,  63,  69, 
      0,   0,   9, 242,   0,  16, 
      0,   3,   0,   0,   0,  70, 
     16,  16,   0,   1,   0,   0, 
      0,  70, 126,  16,   0,   0, 
      0,   0,   0,   0,  96,  16, 
      0,   0,   0,   0,   0,  69, 
      0,   0,   9, 242,   0,  16, 
      0,   4,   0,   0,   0,  70, 
     16,  16,   0,   1,   0,   0, 
      0,  70, 126,  16,   0,   1, 
      0,   0,   0,   0,  96,  16, 
      0,   1,   0,   0,   0,  50, 
      0,   0,  12, 242,   0,  16, 
      0,   3,   0,   0,   0,  70, 
     14,  16,   0,   4,   0,   0, 
      0,   2,  64,   0,   0,   0, 
      0, 128,  64,   0,   0, 128, 
     64,   0,   0, 128,  64,   0, 
      0, 128,  64,  70,  14,  16, 
      0,   3,   0,   0,   0,   0, 
      0,   0,   7, 242,   0,  16, 
      0,   0,   0,   0,   0,  70, 
     14,  16,   0,   0,   0,   0, 
      0,  70,  14,  16,   0,   3, 
      0,   0,   0,   1,   0,   0, 
      7,  18,   0,  16,   0,   1, 
      0,   0,   0,  10,   0,  16, 
      0,   1,   0,   0,   0,  10, 
      0,  16,   0,   2,   0,   0, 
      0,   1,   0,   0,   7,  18, 
      0,  16,   0,   1,   0,   0, 
      0,  26,   0,  16,   0,   1, 
      0,   0,   0,  10,   0,  16, 
      0,   1,   0,   0,   0,   1, 
      0,   0,   7,  18,   0,  16, 
      0,   1,   0,   0,   0,  26, 
      0,  16,   0,   2,   0,   0, 
      0,  10,   0,  16,   0,   1, 
      0,   0,   0,  55,   0,   0, 
      9, 242,   0,  16,   0,   0, 
      0,   0,   0,   6,   0,  16, 
      0,   1,   0,   0,   0,  70, 
     14,  16,   0,   0,   0,   0, 
      0,  70,  14,  16,   0,   3, 
      0,   0,   0,  49,   0,   0, 
      8,  18,   0,  16,   0,   1, 
      0,   0,   0,   1,  64,   0, 
      0,   0,   0,   0,   0,  58, 
    128,  32,   0,   0,   0,   0, 
      0,  33,   0,   0,   0,  55, 
      0,   0,   9, 242,  32,  16, 
      0,   0,   0,   0,   0,   6, 
      0,  16,   0,   1,   0,   0, 
      0,  70,  14,  16,   0,   0, 
      0,   0,   0,  70,  14,  16, 
      0,   3,   0,   0,   0,  62, 
      0,   0,   1,  83,  84,  65, 
     84, 116,   0,   0,   0,  32, 
      0,   0,   0,   5,   0,   0, 
      0,   0,   0,   0,   0,   2, 
      0,   0,   0,  12,   0,   0, 
      0,   0,   0,   0,   0,  12, 
      0,   0,   0,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   2,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 169,  21,   0,   0,   0, 
      0,   0,   0,  77, 111, 116, 
    105, 111, 110,  66, 108, 117, 
    114,   0,  64,   2,   0,   0, 
     68,  88,  66,  67, 228,  77, 
     10,   2, 174,  22,  22, 158, 
    217, 105, 111, 180,  28, 223, 
     97, 175,   1,   0,   0,   0, 
     64,   2,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    140,   0,   0,   0, 192,   0, 
      0,   0,  24,   1,   0,   0, 
    196,   1,   0,   0,  82,  68, 
     69,  70,  80,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     28,   0,   0,   0,   0,   4, 
    254, 255,   0,   1,   0,   0, 
     28,   0,   0,   0,  77, 105, 
     99, 114, 111, 115, 111, 102, 
    116,  32,  40,  82,  41,  32, 
     72,  76,  83,  76,  32,  83, 
    104,  97, 100, 101, 114,  32, 
     67, 111, 109, 112, 105, 108, 
    101, 114,  32,  57,  46,  51, 
     48,  46,  57,  54,  48,  46, 
     56,  50,  50,  57,   0, 171, 
    171, 171,  73,  83,  71,  78, 
     44,   0,   0,   0,   1,   0, 
      0,   0,   8,   0,   0,   0, 
     32,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,   7,   3,   0,   0, 
     80,  79,  83,  73,  84,  73, 
     79,  78,   0, 171, 171, 171, 
     79,  83,  71,  78,  80,   0, 
      0,   0,   2,   0,   0,   0, 
      8,   0,   0,   0,  56,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
     15,   0,   0,   0,  68,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   1,   0,   0,   0, 
      3,  12,   0,   0,  83,  86, 
     95,  80, 111, 115, 105, 116, 
    105, 111, 110,   0,  84,  69, 
     88,  67,  79,  79,  82,  68, 
      0, 171, 171, 171,  83,  72, 
     68,  82, 164,   0,   0,   0, 
     64,   0,   1,   0,  41,   0, 
      0,   0,  95,   0,   0,   3, 
     50,  16,  16,   0,   0,   0, 
      0,   0, 103,   0,   0,   4, 
    242,  32,  16,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
    101,   0,   0,   3,  50,  32, 
     16,   0,   1,   0,   0,   0, 
     54,   0,   0,   5,  50,  32, 
     16,   0,   0,   0,   0,   0, 
     70,  16,  16,   0,   0,   0, 
      0,   0,  54,   0,   0,   8, 
    194,  32,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 128,  63,  50,   0, 
      0,  15,  50,  32,  16,   0, 
      1,   0,   0,   0,  70,  16, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,  63,   0,   0,   0, 191, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,  63,   0,   0, 
      0,  63,   0,   0,   0,   0, 
      0,   0,   0,   0,  62,   0, 
      0,   1,  83,  84,  65,  84, 
    116,   0,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
    104,  30,   0,   0,   0,   0, 
      0,   0, 168,   4,   0,   0, 
     68,  88,  66,  67,  81,  29, 
    232,  23, 189,  79, 164,  41, 
     68, 117, 216, 121, 120, 111, 
    210,  38,   1,   0,   0,   0, 
    168,   4,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    240,   2,   0,   0,  72,   3, 
      0,   0, 124,   3,   0,   0, 
     44,   4,   0,   0,  82,  68, 
     69,  70, 180,   2,   0,   0, 
      1,   0,   0,   0, 176,   0, 
      0,   0,   3,   0,   0,   0, 
     28,   0,   0,   0,   0,   4, 
    255, 255,   0,   1,   0,   0, 
    128,   2,   0,   0, 124,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
    142,   0,   0,   0,   2,   0, 
      0,   0,   5,   0,   0,   0, 
      4,   0,   0,   0, 255, 255, 
    255, 255,   0,   0,   0,   0, 
      1,   0,   0,   0,  12,   0, 
      0,   0, 159,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0, 115,  97, 
    109, 112, 108, 101, 114,  83, 
     99, 101, 110, 101,  67, 111, 
    108, 111, 114,   0,  98, 117, 
    102, 102, 101, 114,  83,  99, 
    101, 110, 101,  67, 111, 108, 
    111, 114,   0, 112,  97, 114, 
     97, 109, 115,  79, 110, 108, 
    121,  79, 110,  99, 101,   0, 
    171, 171, 159,   0,   0,   0, 
      8,   0,   0,   0, 200,   0, 
      0,   0,  32,   2,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 136,   1,   0,   0, 
      0,   0,   0,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
    156,   1,   0,   0,   0,   0, 
      0,   0, 172,   1,   0,   0, 
     32,   0,   0,   0, 240,   0, 
      0,   0,   0,   0,   0,   0, 
    192,   1,   0,   0,   0,   0, 
      0,   0, 208,   1,   0,   0, 
     16,   1,   0,   0, 228,   0, 
      0,   0,   0,   0,   0,   0, 
    228,   1,   0,   0,   0,   0, 
      0,   0, 244,   1,   0,   0, 
    244,   1,   0,   0,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   2,   0,   0,   0,   0, 
      0,   0,  24,   2,   0,   0, 
      0,   2,   0,   0,  16,   0, 
      0,   0,   0,   0,   0,   0, 
     40,   2,   0,   0,   0,   0, 
      0,   0,  56,   2,   0,   0, 
     16,   2,   0,   0,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   2,   0,   0,   0,   0, 
      0,   0,  70,   2,   0,   0, 
     24,   2,   0,   0,   4,   0, 
      0,   0,   2,   0,   0,   0, 
     92,   2,   0,   0,   0,   0, 
      0,   0, 108,   2,   0,   0, 
     28,   2,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
     92,   2,   0,   0, 124,   2, 
      0,   0,  98, 108, 111, 111, 
    109,  71,  97, 116, 104, 101, 
    114,  83,  97, 109, 112, 108, 
    101, 115,   0, 171,   1,   0, 
      3,   0,   1,   0,   4,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   0,  98, 108, 111, 111, 
    109,  66, 108, 117, 114,  83, 
     97, 109, 112, 108, 101, 115, 
      0, 171, 171, 171,   1,   0, 
      3,   0,   1,   0,   4,   0, 
     15,   0,   0,   0,   0,   0, 
      0,   0,  98, 108, 111, 111, 
    109,  66, 108, 117, 114,  87, 
    101, 105, 103, 104, 116, 115, 
      0, 171, 171, 171,   0,   0, 
      3,   0,   1,   0,   1,   0, 
     15,   0,   0,   0,   0,   0, 
      0,   0,  98, 108, 111, 111, 
    109,  66, 108, 117, 114,  80, 
    105, 120, 101, 108,  68, 105, 
    114,   0, 171, 171,   1,   0, 
      3,   0,   1,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 115,  99, 114, 101, 
    101, 110,  83, 105, 122, 101, 
     73, 110, 118,   0, 171, 171, 
      1,   0,   3,   0,   1,   0, 
      4,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 102, 105, 
    108, 116, 101, 114,  83, 105, 
    122, 101,  73, 110, 118,   0, 
    109, 111, 116, 105, 111, 110, 
     66, 108, 117, 114,  70, 114, 
     97, 109, 101,  87, 101, 105, 
    103, 104, 116,   0,   0,   0, 
      3,   0,   1,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 108, 111,  97, 100, 
     80, 114, 111, 103, 114, 101, 
    115, 115,   0, 171, 171, 171, 
      0,   0,   0,   0,  77, 105, 
     99, 114, 111, 115, 111, 102, 
    116,  32,  40,  82,  41,  32, 
     72,  76,  83,  76,  32,  83, 
    104,  97, 100, 101, 114,  32, 
     67, 111, 109, 112, 105, 108, 
    101, 114,  32,  57,  46,  51, 
     48,  46,  57,  54,  48,  46, 
     56,  50,  50,  57,   0, 171, 
    171, 171,  73,  83,  71,  78, 
     80,   0,   0,   0,   2,   0, 
      0,   0,   8,   0,   0,   0, 
     56,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,  15,   0,   0,   0, 
     68,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   1,   0, 
      0,   0,   3,   3,   0,   0, 
     83,  86,  95,  80, 111, 115, 
    105, 116, 105, 111, 110,   0, 
     84,  69,  88,  67,  79,  79, 
     82,  68,   0, 171, 171, 171, 
     79,  83,  71,  78,  44,   0, 
      0,   0,   1,   0,   0,   0, 
      8,   0,   0,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
     15,   0,   0,   0,  83,  86, 
     95,  84,  97, 114, 103, 101, 
    116,   0, 171, 171,  83,  72, 
     68,  82, 168,   0,   0,   0, 
     64,   0,   0,   0,  42,   0, 
      0,   0,  89,   0,   0,   4, 
     70, 142,  32,   0,   0,   0, 
      0,   0,  34,   0,   0,   0, 
     90,   0,   0,   3,   0,  96, 
     16,   0,   0,   0,   0,   0, 
     88,  24,   0,   4,   0, 112, 
     16,   0,   0,   0,   0,   0, 
     85,  85,   0,   0,  98,  16, 
      0,   3,  50,  16,  16,   0, 
      1,   0,   0,   0, 101,   0, 
      0,   3, 242,  32,  16,   0, 
      0,   0,   0,   0, 104,   0, 
      0,   2,   1,   0,   0,   0, 
     69,   0,   0,   9, 242,   0, 
     16,   0,   0,   0,   0,   0, 
     70,  16,  16,   0,   1,   0, 
      0,   0,  70, 126,  16,   0, 
      0,   0,   0,   0,   0,  96, 
     16,   0,   0,   0,   0,   0, 
     54,   0,   0,   5, 114,  32, 
     16,   0,   0,   0,   0,   0, 
     70,   2,  16,   0,   0,   0, 
      0,   0,  54,   0,   0,   6, 
    130,  32,  16,   0,   0,   0, 
      0,   0,  42, 128,  32,   0, 
      0,   0,   0,   0,  33,   0, 
      0,   0,  62,   0,   0,   1, 
     83,  84,  65,  84, 116,   0, 
      0,   0,   4,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   2,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 180,  32, 
      0,   0,   0,   0,   0,   0, 
      4,   0,   0,   0,  32,   2, 
      0,   0,   0,   0,   0,   0, 
      8,   0,   0,   0, 255, 255, 
    255, 255,   0,   0,   0,   0, 
     54,   0,   0,   0,  26,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 101,   0, 
      0,   0,  73,   0,   0,   0, 
      0,   0,   0,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 152,   0,   0,   0, 
    124,   0,   0,   0,   0,   0, 
      0,   0,  16,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
    204,   0,   0,   0, 176,   0, 
      0,   0,   0,   0,   0,   0, 
    244,   1,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 250,   0, 
      0,   0, 222,   0,   0,   0, 
      0,   0,   0,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   8,   1,   0,   0, 
    176,   0,   0,   0,   0,   0, 
      0,   0,  16,   2,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     50,   1,   0,   0,  22,   1, 
      0,   0,   0,   0,   0,   0, 
     24,   2,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  72,   1, 
      0,   0,  22,   1,   0,   0, 
      0,   0,   0,   0,  28,   2, 
      0,   0,  85,   1,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0, 127,   1,   0,   0, 
     99,   1,   0,   0,   0,   0, 
      0,   0, 255, 255, 255, 255, 
      0,   0,   0,   0, 144,   1, 
      0,   0,  99,   1,   0,   0, 
      0,   0,   0,   0, 255, 255, 
    255, 255,   0,   0,   0,   0, 
    198,   1,   0,   0, 170,   1, 
      0,   0,   0,   0,   0,   0, 
    255, 255, 255, 255,   3,   0, 
      0,   0,  46,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0, 216,   1,   0,   0, 
     47,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
    228,   1,   0,   0,  45,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0, 240,   1, 
      0,   0,   0,   0,   0,   0, 
    252,   1,   0,   0, 170,   1, 
      0,   0,   0,   0,   0,   0, 
    255, 255, 255, 255,   3,   0, 
      0,   0,  46,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,  10,   2,   0,   0, 
     47,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
     22,   2,   0,   0,  45,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,  34,   2, 
      0,   0,   0,   0,   0,   0, 
     46,   2,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
     53,   2,   0,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      6,   0,   0,   0,   0,   0, 
      0,   0,   7,   0,   0,   0, 
    128,   4,   0,   0,   7,   0, 
      0,   0,   0,   0,   0,   0, 
      7,   0,   0,   0,  96,  11, 
      0,   0, 104,  11,   0,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   0,   6,   0,   0,   0, 
      0,   0,   0,   0,   7,   0, 
      0,   0, 177,  13,   0,   0, 
      7,   0,   0,   0,   0,   0, 
      0,   0,   7,   0,   0,   0, 
     77,  19,   0,   0,  85,  19, 
      0,   0,   2,   0,   0,   0, 
      0,   0,   0,   0,   6,   0, 
      0,   0,   0,   0,   0,   0, 
      7,   0,   0,   0, 161,  21, 
      0,   0,   7,   0,   0,   0, 
      0,   0,   0,   0,   7,   0, 
      0,   0,  85,  30,   0,   0, 
     93,  30,   0,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      6,   0,   0,   0,   0,   0, 
      0,   0,   7,   0,   0,   0, 
    172,  32,   0,   0,   7,   0, 
      0,   0,   0,   0,   0,   0, 
      7,   0,   0,   0,  96,  37, 
      0,   0
};
